#include <iostream>

using namespace std;

int main()
{
    cout << "Learning about the errors generated by the compiler" << endl;
    cout << "---------------------------------------------------" << endl;
    cout << "NOTE: In this program there are supposed to be errors. So you do not need to fix them" << endl;

    cout << "Syantax Error: no parenthesis to close for condition" << endl;

    for (int i = 1; i <= 10; i++
    {
        cout << i << endl;
    }

    cout << "---------------------------------------------------" << endl;

    cout << "Declaration Error: i is not defined (i is defined later in the code but there is still an error)" << endl;


    while (i <= 10)
    {
        cout << i << endl;
        ++i;
    }

    cout << "Type Error: i has a type of int but holds a string"

    int i = "hello!";

    return 0;
}